language: php
php:
  - 5.3
before_script:
  - pear config-set preferred_state alpha
  - pear channel-discover public.intraface.dk
  - pear channel-discover pearhub.org
  - pear install --force intrafacepublic/Ilib_Variable-1.0.1
  - pear install PHP_CodeSniffer
  - pear install intrafacepublic/Document_Cpdf    
  - phpenv rehash
script: 
  - phpunit --configuration test/phpunit.example.xml ./test
  - phpcs src
