sudo: false
language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
install:
  - composer self-update
  - composer install --no-interaction
before_script:
  - mkdir ./test/temp
script:
  - ./vendor/bin/phpunit --coverage-text
  - ./vendor/bin/phpcs --standard=phpcs.xml src
after_script:
  - ls -al ./test/temp
